20 player view task completion bar
NamrataAcharya02/IRLAmongUs pull request #69
Opened 2023-11-25 15:42 UTC by pinlunix

Progress bar with functions that update the progress bar whenever a button (for the purpose of a task marked as completed) is pressed. Added comments to code.

2023-11-26 05:24 UTC, bluepaw59 commented
looks good, we'll keep the branch open after the merge to get the backend magic in

2023-11-27 23:46 UTC, richardkhillah commented
view status bar and increment functionality look good.

Get rid of the story related code (i.e., get rid of the "Select a task list" and "add task" sections not related to viewing a status bar or calling emergency meeting (since I see emergency meeting was merged in last week)).

You can always delete, recommit, push, undo the delete, recommit, then re-push (after merged into main).

2023-11-27 23:51 UTC, richardkhillah requested changes
All looks good, just remove non-player-story related items and okay to merge

2023-11-27 23:51 UTC, richardkhillah commented on src/pages/PlayerGame.js
> +            <FrontendTaskList></FrontendTaskList>
Looks like this component renders Admin-related tasklist functionality. I think this should be altered since this story is for player and PlayerGame

2023-11-28 00:16 UTC, bluepaw59 approved these changes
Looks good

2023-11-28 00:37 UTC, richardkhillah approved these changes

2023-11-28 00:45 UTC, merged